# Useful Resources

## Resources on Theories

**Math supplemental notes**

Stanford Machine Learning math notes

http://cs229.stanford.edu/materials.html

Highlights:

[(pdf)](http://cs229.stanford.edu/section/cs229-linalg.pdf) Linear Algebra Review and Reference

[(pdf)](http://cs229.stanford.edu/section/cs229-prob.pdf) Probability Theory Review

**Textbooks**

Course Textbook

Artificial Intelligence: A Modern Approach (3rd Edition)

Further readings:

ISLR: An Introduction to Statistical Learning with Applications in R

http://www-bcf.usc.edu/~gareth/ISL/

ESL: The Elements of Statistical Learning: Data Mining, Inference, and Prediction. Second Edition

http://statweb.stanford.edu/~tibs/ElemStatLearn/

**MOOC websites**

In companion with ISLR:

https://www.r-bloggers.com/in-depth-introduction-to-machine-learning-in-15-hours-of-expert-videos/

Coursera Stanford Machine Learning

https://www.coursera.org/learn/machine-learning/home/welcome

CMU Data Mining

http://www.stat.cmu.edu/~ryantibs/datamining/

**Others**

Visual Information Theory

http://colah.github.io/posts/2015-09-Visual-Information/

## Resources on Coding

**Project Kaggle page**

https://www.kaggle.com/c/two-sigma-connect-rental-listing-inquiries

**bookdown**

The package that builds this website.

https://bookdown.org/yihui/bookdown/

**prism.js**

Alternative highlight javascript

http://prismjs.com/#basic-usage

### R Resources

**Official Manuals**

https://cran.r-project.org/manuals.html

R Introduction

[(pdf)](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf) R Intro

**Data Visualization in R with ggplot2**

http://varianceexplained.org/RData/code/code_lesson2/

**ggplot2 Documentation**

http://docs.ggplot2.org/current/

**Plotting NYC Map**

https://www.kaggle.com/enrique1500/two-sigma-connect-rental-listing-inquiries/rental-listing-ny-map

**TensorFlow in R**

https://rstudio.github.io/tensorflow/index.html

MNIST For ML Beginners (Softmax Regression)

https://rstudio.github.io/tensorflow/tutorial_mnist_beginners.html

Deep MNIST for Experts (Convolutional Neural Network)

https://rstudio.github.io/tensorflow/tutorial_mnist_pros.html

https://rstudio.github.io/tensorflow/tutorial_mnist_pros.html

### Python Resources

**PyCharm: A Python IDE**

https://www.jetbrains.com/pycharm/

**TensorFlow in Python**

https://www.tensorflow.org/
